In [1]:
#imports 
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
df=pd.read_csv("churn_Data.csv")
print(df.index)
print("All columns are")
ai=0
for i in df:
    print(ai,i)
    ai+=1

RangeIndex(start=0, stop=200, step=1)
All columns are
0 tenure
1 age
2 address
3 income
4 ed
5 employ
6 equip
7 callcard
8 wireless
9 churn

In [3]:
df.shape

(200, 10)

In [4]:
df.head()

   tenure  age  address  income  ed  employ  equip  callcard  wireless  churn
0      11   33        7     136   5       5      0         1         1      1
1      33   33       12      33   2       0      0         0         0      1
2      23   30        9      30   1       2      0         0         0      0
3      38   35        5      76   2      10      1         1         1      0
4       7   35       14      80   2      15      0         1         0      0

In [5]:
df.sample(n=10)

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
57,5,30,3,46,4,7,1,0,0,1
18,64,25,4,76,3,2,1,1,0,0
39,43,43,3,55,4,18,1,1,1,0
72,28,36,3,42,3,7,0,1,0,0
108,32,34,0,38,1,10,0,1,0,0
132,36,45,22,117,3,15,0,0,0,0
28,3,24,2,20,2,3,0,1,0,0
65,53,35,15,59,3,5,0,1,0,0
100,1,30,3,135,4,3,1,1,0,1
125,72,75,48,14,2,6,0,1,0,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tenure    200 non-null    int64
 1   age       200 non-null    int64
 2   address   200 non-null    int64
 3   income    200 non-null    int64
 4   ed        200 non-null    int64
 5   employ    200 non-null    int64
 6   equip     200 non-null    int64
 7   callcard  200 non-null    int64
 8   wireless  200 non-null    int64
 9   churn     200 non-null    int64
dtypes: int64(10)
memory usage: 15.8 KB

In [7]:
df.isnull()

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
195,False,False,False,False,False,False,False,False,False,False
196,False,False,False,False,False,False,False,False,False,False
197,False,False,False,False,False,False,False,False,False,False
198,False,False,False,False,False,False,False,False,False,False
199,False,False,False,False,False,False,False,False,False,False

In [8]:
print(df.isnull().sum())
print("The data seems to not have any null values")

tenure      0
age         0
address     0
income      0
ed          0
employ      0
equip       0
callcard    0
wireless    0
churn       0
dtype: int64
The data seems to not have any null values

In [9]:
(df.duplicated())
print('Duplicate values :',df.duplicated().sum())
df[df.duplicated()]

Duplicate values : 0

Empty DataFrame
Columns: [tenure, age, address, income, ed, employ, equip, callcard, wireless, churn]
Index: []

In [10]:
df.describe()

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
count,200.000000,200.000000,200.000000,200.000000,200.00000,200.00000,200.000000,200.000000,200.000000,200.000000
mean,35.505000,41.165000,11.650000,75.130000,2.82500,10.22500,0.425000,0.705000,0.290000,0.290000
std,21.640971,13.076803,10.158419,128.430468,1.28555,8.95743,0.495584,0.457187,0.454901,0.454901
min,1.000000,19.000000,0.000000,9.000000,1.00000,0.00000,0.000000,0.000000,0.000000,0.000000
25%,16.750000,31.000000,3.000000,31.000000,2.00000,3.00000,0.000000,0.000000,0.000000,0.000000
50%,33.500000,40.000000,9.000000,48.000000,3.00000,7.50000,0.000000,1.000000,0.000000,0.000000
75%,55.250000,51.000000,18.000000,80.000000,4.00000,17.00000,1.000000,1.000000,1.000000,1.000000
max,72.000000,76.000000,48.000000,1668.000000,5.00000,44.00000,1.000000,1.000000,1.000000,1.000000

In [19]:
'''
def plot(a):
    sns.lineplot(y=a)
bi = 0
for i in df:
    plot(i)
    bi+=1
'''

ValueError: Could not interpret value `tenure` for `y`. Value is a string, but `data` was not passed.