In [2]:
#imports 
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [4]:
df=pd.read_csv("churn_Data.csv")
print(df.index)
print("All columns are")
ai=0
for i in df:
    print(ai,i)
    ai+=1

RangeIndex(start=0, stop=200, step=1)
All columns are
0 tenure
1 age
2 address
3 income
4 ed
5 employ
6 equip
7 callcard
8 wireless
9 churn

In [19]:
df.shape

(200, 10)

In [17]:
df.head()

   tenure  age  address  income  ed  employ  equip  callcard  wireless  churn
0      11   33        7     136   5       5      0         1         1      1
1      33   33       12      33   2       0      0         0         0      1
2      23   30        9      30   1       2      0         0         0      0
3      38   35        5      76   2      10      1         1         1      0
4       7   35       14      80   2      15      0         1         0      0

In [20]:
df.sample(n=10)

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
114,9,24,3,26,4,1,1,0,0,0
51,26,39,15,58,4,9,0,1,1,0
138,45,34,14,43,4,0,1,0,0,1
66,37,76,38,117,4,21,0,1,0,0
24,53,22,1,25,4,0,1,1,0,0
0,11,33,7,136,5,5,0,1,1,1
195,55,44,24,83,1,23,0,1,0,0
61,60,45,23,117,4,11,1,1,1,0
143,63,37,1,45,4,9,1,1,0,0
103,44,45,19,88,1,21,0,1,0,0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tenure    200 non-null    int64
 1   age       200 non-null    int64
 2   address   200 non-null    int64
 3   income    200 non-null    int64
 4   ed        200 non-null    int64
 5   employ    200 non-null    int64
 6   equip     200 non-null    int64
 7   callcard  200 non-null    int64
 8   wireless  200 non-null    int64
 9   churn     200 non-null    int64
dtypes: int64(10)
memory usage: 15.8 KB

In [11]:
df.isnull()

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
195,False,False,False,False,False,False,False,False,False,False
196,False,False,False,False,False,False,False,False,False,False
197,False,False,False,False,False,False,False,False,False,False
198,False,False,False,False,False,False,False,False,False,False
199,False,False,False,False,False,False,False,False,False,False

In [21]:
print(df.isnull().sum())
print("The data seems to not have any null values")

tenure      0
age         0
address     0
income      0
ed          0
employ      0
equip       0
callcard    0
wireless    0
churn       0
dtype: int64
The data seems to not have any null values

In [25]:
(df.duplicated())
print('Duplicate values :',df.duplicated().sum())
df[df.duplicated()]

Duplicate values : 0

Empty DataFrame
Columns: [tenure, age, address, income, ed, employ, equip, callcard, wireless, churn]
Index: []